### ISSUE TITLE
Crash when running bower-outdated with specific package (AdminLTE)

### ISSUE THREAD

**Issue by drbarto** [HugoCapocci/bower-outdated#1]
Hi there,

first of all, thanks for the great tool :)

I tried to run `bower-outdated` but got the following error:

    $ bower-outdated
    /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:155
                    throw e;
                    ^

    Error: Package AdminLTE not found
        at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)
        at /usr/local/lib/node_modules/bower/lib/core/resolverFactory.js:206:23
        at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
        at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
        at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)
        at flush (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:125:13)
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)

The error is somehow caused by the package AdminLTE. Here's how it is listed in `bower.json`:

      "dependencies": { 
        "AdminLTE": "adminlte#^2.3.3", ...
      }
 
I removed that dependency and `bower-outdated` worked like a charm.

**Comment by HugoCapocci** [comment]
Sorry for the late answer; busy working on react/webpack since a few weeks ^^
I'm not very using bower anymore, but I'll try to fix this issue, thank a lot for your very descriptive case @drbarto

**Comment by HugoCapocci** [comment]
fixed in release 0.8.0
